##### THIS ALLOWS US TO DEPLOY THE SITE FROM A GIT REPO ######
---
deployment:
  tasks:
    - export DEPLOYPATH=/home/illustra/public_html/custom.illustrationwizard.com/phh
   - export DEPLOYPATH=/home/example/public_html/
    - /bin/cp -R images $DEPLOYPATH

    